### ISSUE TITLE
Releasing 2.4.x versions

### ISSUE THREAD

**Issue by wltjr** [eclipse-ee4j/jaxb-api#89]
I am curious about 2.4.x versions. The [previous repository](https://github.com/javaee/jaxb-spec/releases) had a [2.4.0 release](https://github.com/javaee/jaxb-spec) in addition to 2.3.1. This repo released 2.3.2. Will there also be a 2.4.1 release, or any 2.4.x? I am trying to figure out what to do with [2.4.0](https://github.com/Obsidian-StudiosInc/os-xtoo/tree/master/dev-java/jaxb-api), keep or remove and revert to 2.3.2. I am adding 2.3.2 from this repo, but 2.4.0 will be used instead due to being a higher version. That is why I am trying to decide on keeping 2.4.0 or not.

Also, will the versions of jaxb-api be kept in sync with [jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri/releases), or just a coincidence they are both on 2.3.2?

Thank you!

**Comment by bravehorsie** [comment]
2.4.0-b180830.0359 is [almost identical as are 2.3.1 and 2.3.2 respectively](https://github.com/javaee/jaxb-spec/commits/master). If you order releases by date instead of its number the latest is 2.3.2 for now. 

@m0mus @lukasj Any ideas on why original intention to continue with 2.4.0 numbering was reverted to 2.3.X after there were 2.4.0-XXXX artifacts in central?

**Comment by wltjr** [comment]
@bravehorsie thanks for the information! I can always remove the package for 2.4.0, which clears up the situation on my end. Though would be good to know the backstory you are asking others, hopefully they will chime in there.

**Comment by Tomas-Kraus** [comment]
Jakarta EE 8 release is version 2.3.2, which is next version of 2.3.1 released from Oracle repository.
2.4.0-SNAPSHOT is in master branch and will be used for next JAXB API specification update release.
